"use client"

import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { AlertTriangle } from "lucide-react"

interface TrainingDisclaimerProps {
  onAcknowledge: () => void
  trainingTitle: string
}

export function TrainingDisclaimer({ onAcknowledge, trainingTitle }: TrainingDisclaimerProps) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-slate-100 dark:from-slate-950 dark:via-blue-950 dark:to-slate-900 flex items-center justify-center p-4">
      <Card className="max-w-3xl w-full p-8 shadow-xl border-2 border-blue-200 dark:border-blue-800">
        <div className="flex items-start gap-4 mb-6">
          <div className="flex-shrink-0 w-12 h-12 rounded-full bg-blue-100 dark:bg-blue-900 flex items-center justify-center">
            <AlertTriangle className="w-6 h-6 text-blue-600 dark:text-blue-400" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">
              Before You Begin: {trainingTitle}
            </h2>
            <p className="text-sm text-slate-600 dark:text-slate-400">
              Please review the following information carefully
            </p>
          </div>
        </div>

        <div className="space-y-6 text-sm text-slate-700 dark:text-slate-300">
          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Disclaimer:</h3>
            <p>
              This AI coaching simulation is provided for coaching and development purposes. AI-generated guidance may
              be incomplete or inaccurate, so please use your judgement when applying it. For clarification or support,
              speak with your manager or coaching lead.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Privacy Notice:</h3>
            <p>
              This coaching platform is operated by a third-party provider on behalf of your organization. The platform
              uses AI-powered role-play simulations to support communication, coaching, and skill development.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Data Collected:</h3>
            <p className="mb-2">Personal data may be collected through your use of the platform, including:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Basic user identifiers (e.g., employee/user ID) for account setup</li>
              <li>Transcripts of your interactions with the AI</li>
              <li>Feedback scores and coaching insights generated by the system</li>
              <li>Information you input during simulations</li>
              <li>Technical device and usage data (e.g., IP address, browser type, access times)</li>
            </ul>
            <p className="mt-2">
              Sensitive information (e.g., health data, biometrics) is not intentionally collected. Please avoid sharing
              such information during simulations.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">How Your Data Is Used:</h3>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>To operate the platform and manage user accounts</li>
              <li>To run AI simulations, generate feedback, and track development</li>
              <li>To support analytics that improve coaching quality</li>
            </ul>
            <p className="mt-2">
              Your organization may also use this information to evaluate engagement capabilities, track progress, and
              guide professional development.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Data Sharing:</h3>
            <p>
              Your personal data may be shared only with authorized third parties involved in providing, supporting, or
              improving the coaching platform, or when required by law.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Data Retention:</h3>
            <p>
              Data may be kept by the platform provider for the duration of service plus a short retention period. Your
              organization may retain data in line with internal policies and legal requirements.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Security:</h3>
            <p>Reasonable safeguards are used to protect your data from loss, misuse, or unauthorized access.</p>
          </div>

          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Your Rights:</h3>
            <p>
              Depending on local laws, you may request access, correction, deletion, or restriction of your personal
              data through your organization's established data rights process. Identity verification may be required.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white mb-2">Contact:</h3>
            <p>
              For questions or data requests, contact your organization's privacy or data protection representative.
            </p>
          </div>
        </div>

        <div className="mt-8 flex justify-center">
          <Button
            onClick={onAcknowledge}
            size="lg"
            className="bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white px-12"
          >
            Acknowledge
          </Button>
        </div>
      </Card>
    </div>
  )
}
